### PR TITLE
Add grpc-lb-server

### PR DESCRIPTION
**Pull request by RussellLuo**
Fixed issue #15.

### CODE REVIEW

**Comment by dim** [comment]
@RussellLuo thanks, but I don't quite understand why you are connecting your server to consul? One of the goals of this project is to detach the servers from consul, i.e. make consul a transparent backend for LB instances (e.g. https://github.com/bsm/grpclb/blob/master/cmd/grpc-lb-consul/main.go). 

There is a much simpler example of a server implementation in [godoc](https://godoc.org/github.com/bsm/grpclb/load#ex-package), here's the [code](https://github.com/bsm/grpclb/blob/master/load/example_test.go#L27)

**Comment by RussellLuo** [comment]
Please point out if i am mistaken. As far as I can see, if we don't register the server (or backend) to Consul, how can the Consul-backed LB [find available server (or backend) entries from Consul](https://github.com/bsm/grpclb/blob/master/discovery/consul/consul.go#L43)?

**Comment by dim** [comment]
@RussellLuo the grpclb follows the same process as outlined in https://github.com/grpc/grpc/blob/master/doc/load-balancing.md

1. the client connects to the LB and requests a list of servers for service `x`
2. (on first request) the LB connects to Backend (consul) and requests all addresses of `x`
3. the LB connects to each Server instance of `x` and (periodically) requests load information
4. the LB returns the list of known Server addresses to the Client, scored and prioritised by load
5. the Client connects to the Server with the best score

See https://yuml.me/64216780. As you can see the Servers never talk to Consul directly, neither do the Clients. The LB is the central mediator between Clients and Servers and use Consul as the backend. 

For Consul to know about the Server, the Server obviously needs to announce itself but that is something that should be (ideally) solved on an operational rather than the app level. At least, it is very specific to the underlying infrastructure. Internally, we have experience with e.g. https://github.com/gliderlabs/registrator or https://github.com/CiscoCloud/marathon-consul but there are tons of other tools for this purpose (even some simple shell wrapper scripts using `curl`).

**Comment by RussellLuo** [comment]
@dim Thanks for your detailed reply!

I think I can see your point now :) I just confused the infrastructure-level work with the application-level work, both of which are intentionally differentiated by grpclb (and I think it seems good).

**Pull request closed without merging**
